version: 2.1

workflows:
    build:
        jobs:
            - build

jobs:
    build:
        machine:
            image: mcr.microsoft.com/dotnet/framework/sdk:4.8
            resource_class: windows.medium
            shell: powershell.exe -NoProfile -ExecutionPolicy Bypass
        steps:
            - checkout
            - run:
                name: Build
                command: dotnet build --configuration Release
            - run:
                name: Run
                command: sample-framework-circle\bin\Release\net462\sample-framework-circle.exe
