version: 2.1

orbs:
  win: sandbox/windows-tools@dev:preview

workflows:
  build:
    jobs:
      - build

jobs:
    build:
        environment:
            - NUGET_VERSION: "4.4.1"
            - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
            - ROSLYN_COMPILER_LOCATION: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\MSBuild\\Current\\Bin\\Roslyn"
            - PATH: "C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\dotnet\\;C:\\Users\\ContainerAdministrator\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\NuGet;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\TestAgent\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\MSBuild\\Current\\Bin;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.8 Tools;C:\\Program Files (x86)\\Microsoft SDKs\\ClickOnce\\SignTool;C:\\MinGit\\cmd;"
        executor: win/preview-default
        steps:
            - checkout
            # Install .NET 4.8
            - run:  |
                "Invoke-WebRequest -Uri "https://download.visualstudio.microsoft.com/download/pr/7afca223-55d2-470a-8edc-6a1739ae3252/abd170b4b0ec15ad0222a809b761a036/ndp48-x86-x64-allos-enu.exe" -OutFile dotnet-framework-installer.exe"
                ".\\dotnet-framework-installer.exe /q"
            - run: |
                "New-Item -Type Directory $Env:ProgramFiles\\NuGet;"
                "Invoke-WebRequest -UseBasicParsing https://dist.nuget.org/win-x86-commandline/v$Env:NUGET_VERSION/nuget.exe -OutFile $Env:ProgramFiles\\NuGet\\nuget.exe"
            # Install VS Test Agent
            - run: |
                "Invoke-WebRequest -UseBasicParsing https://download.visualstudio.microsoft.com/download/pr/4eef3cca-9da8-417a-889f-53212671e83b/50a7f7a24b21910a7cbe093fa150fd31/vs_testagent.exe -OutFile vs_TestAgent.exe;"
                "Start-Process vs_TestAgent.exe -ArgumentList '--quiet', '--norestart', '--nocache' -NoNewWindow -Wait;"
            # Install VS Build Tools
            - run: |
                "Invoke-WebRequest -UseBasicParsing https://download.visualstudio.microsoft.com/download/pr/4da568ff-b8aa-43ab-92ec-a8129370b49a/6fb89b999fed6f395622e004bfe442eb/vs_buildtools.exe -OutFile vs_BuildTools.exe;"
                "setx /M DOTNET_SKIP_FIRST_TIME_EXPERIENCE 1;"
                "Start-Process vs_BuildTools.exe -ArgumentList '--add', 'Microsoft.VisualStudio.Workload.MSBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NetCoreBuildTools', '--add', 'Microsoft.Component.ClickOnce.MSBuild', '--quiet', '--norestart', '--nocache' -NoNewWindow -Wait;"
            # Install .NET 4.8 SDK
            - run: |
                "Invoke-WebRequest -UseBasicParsing https://dotnetbinaries.blob.core.windows.net/dockerassets/sdk_tools48.zip -OutFile sdk_tools48.zip;"
                "Expand-Archive sdk_tools48.zip;"
                "Start-Process msiexec -ArgumentList '/i', 'sdk_tools48\\sdk_tools48.msi', '/quiet', 'VSEXTUI=1' -NoNewWindow -Wait;"
            # Install web targets
            - run: |
                "Invoke-WebRequest -UseBasicParsing https://dotnetbinaries.blob.core.windows.net/dockerassets/MSBuild.Microsoft.VisualStudio.Web.targets.2019.05.zip -OutFile MSBuild.Microsoft.VisualStudio.Web.targets.zip;"
                "Expand-Archive MSBuild.Microsoft.VisualStudio.Web.targets.zip -DestinationPath \\"${Env:ProgramFiles(x86)}\\Microsoft Visual Studio\\2019\\BuildTools\\MSBuild\\Microsoft\\VisualStudio\\v16.0\\";"
            # Install Targeting Packs
            - run: |
                "@('4.0', '4.5.2', '4.6.2', '4.7.2', '4.8') | %{ Invoke-WebRequest -UseBasicParsing https://dotnetbinaries.blob.core.windows.net/referenceassemblies/v${_}.zip -OutFile referenceassemblies.zip; Expand-Archive referenceassemblies.zip -DestinationPath \\"${Env:ProgramFiles(x86)}\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\"; Remove-Item -Force referenceassemblies.zip; }"
